version: '2'

services:
  web:
    build: .
    command: bundle exec foreman start -f ./Procfile.dev -p 3000
    volumes:
      - .:/app
      - rubygems_cache:/rubygems
      - yarn_cache:/app/node_modules
    ports:
      - '3000:3000'
    environment: &default_environment
      GEM_HOME: '/rubygems'
      BUNDLE_PATH: '/rubygems'
      DATABASE_URL: 'postgres://postgres:@postgres:5432'
      REDIS_URL: 'redis://redis:6379'
    depends_on:
      - postgres
      - redis
    # needed for Codeship Pro:
    links:
      - postgres
      - redis

  worker:
    build: .
    command: bundle exec sidekiq -c 4
    volumes:
      - .:/app
      - rubygems_cache:/rubygems
    environment:
      <<: *default_environment
    depends_on:
      - postgres
      - redis
      - web

  postgres:
    image: postgres:9.6
    ports:
      - '5432'
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:3.2
    ports:
      - '6379'

volumes:
  postgres_data:
  rubygems_cache:
  yarn_cache:
